# Generated by Django 5.2 on 2025-04-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsCart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='sucursal_id',
            new_name='sucursal',
        ),
    ]
