# Generated by Django 5.2 on 2025-04-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0002_alter_usuario_table'),
        ('productsCart', '0002_rename_categoria_id_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='authapp.usuario')),
            ],
            options={
                'db_table': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(db_column='carrito_id', on_delete=django.db.models.deletion.CASCADE, to='cart.carrito')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='productsCart.producto')),
            ],
            options={
                'db_table': 'carrito_items',
            },
        ),
    ]
