# Generated by Django 5.2 on 2025-04-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='carritoitem',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
